// Code generated by "stringer -type=FieldType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldTypeSlice-0]
	_ = x[FieldTypeStructure-1]
	_ = x[FieldTypeBaseType-2]
}

const _FieldType_name = "FieldTypeSliceFieldTypeStructureFieldTypeBaseType"

var _FieldType_index = [...]uint8{0, 14, 32, 49}

func (i FieldType) String() string {
	if i < 0 || i >= FieldType(len(_FieldType_index)-1) {
		return "FieldType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldType_name[_FieldType_index[i]:_FieldType_index[i+1]]
}
