

// Code generated by "cofing -t MsgTx"; DO NOT EDIT.
package message

import (
	"bytes"

	"github.com/t10471/bitcoin-coding/basetype"
)

func (m *MsgTx) Decode(b_ *bytes.Buffer) error {
	// Hash
	{
		var err error
		m.Hash, err = basetype.DecodeHash(b_)
		if err != nil {
			return err
		}
	} 
	// Index
	{
		var err error
		m.Index, err = basetype.DecodeUint32(b_)
		if err != nil {
			return err
		}
	}  
	return nil
}

func (m *MsgTx) Encode(b_ *bytes.Buffer) error {
	// Hash
	if err := basetype.EncodeHash(b_, m.Hash); err != nil {
		return err
	} 
	// Index
	if err := basetype.EncodeUint32(b_, m.Index); err != nil {
		return err
	}  
	return nil
}
